### ISSUE TITLE
Bug 1283517 - [doc] create readme.developer on howto write oVirt tests 

### ISSUE THREAD

**Issue by eedri** [lago-project/lago#1]
Description of problem:
In order for lago tests development to start being developed by various teams,
we need to provide a clear and easy README on how to write test for lago.

we'll need to take the 1st dev team in baby steps and make them familiar with the system and how to write and run tests, so they can continue on their own to do it and close the gaps on tests.

migrated from: https://bugzilla.redhat.com/show_bug.cgi?id=1283517

**Comment by david-caro** [comment]
@eedri howdy? :smile:

**Comment by eedri** [comment]
not sure still if this is a Lago bug or ovirt-system-tests bug.

**Comment by eedri** [comment]
This should be part of the ovirt-system-tests feature pages, will be tracked on ovirt JIRA:
https://ovirt-jira.atlassian.net/browse/OVIRT-459
