### ISSUE TITLE
Lago needs to be nice when users are not in the 'lago' group

### ISSUE THREAD

**Issue by ifireball** [lago-project/lago#101]
Lago will just crash now, needs to check and exit immediately with a nice message.

**Comment by david-caro** [comment]
There's already a message actually, in yellow, but it let's you run it as you might not need to be in the lago group to run it (root, privileged users, non-default storage/cache paths)

**Comment by david-caro** [comment]
I don't think that the lago group membership should be required, not even warned at. It should only show something like 'maybe your user should be a member of the lago group?' if there was a permission issue when accessing the cache/store directiories
