### ISSUE TITLE
Allow the libvirt DNS server (dnsmasq) to assign/return FQDNs for VMs on lago-managed networks

### ISSUE THREAD

**Issue by ifireball** [lago-project/lago#104]
Lago can run an internal DNS service in its managed networks, that DNS service however can only assign and resolve plain hostnames. This makes it hard to test applications that require proper full FQDNs to be defined.
Lets add a JSON option to configure domain names for networks, so that hosts on those networks can have their IPs be backwards and forwards resolved to FQDNs as well as short names.

**Comment by david-caro** [comment]
Are you sure that lago is using a dns service at all?

**Comment by ifireball** [comment]
Pretty sure, it sets the gateway IP as the DNS server in the DHCP records it gives. And pinging the VM names from the VMs works

**Comment by david-caro** [comment]
I think it does so though libvirt, setting stuff in the network config of the domains xml, will have to look deeper

**Comment by mykaul** [comment]
Assign it to me - I have a patch for it (+IPv6) @ https://gerrit.ovirt.org/#/c/52530/

**Comment by mykaul** [comment]
This is handled via the fix to issue 116 - closing this one.

**Comment by david-caro** [comment]
for reference: #116
