### ISSUE TITLE
lago-ovirt RPM removal failure

### ISSUE THREAD

**Issue by mykaul** [lago-project/lago#127]
Erasing     : lago-ovirt-0.9.2-1.fc23.noarch                                                                                                                                                               1/247 
FirewallD is not running
FirewallD is not running
error: %preun(python-lago-ovirt-0.9.2-1.fc23.noarch) scriptlet failed, exit status 252

**Comment by david-caro** [comment]
related to #45

**Comment by david-caro** [comment]
fixed on 5deacaec5767df06e2c3a497b9593a72505f8078
