### ISSUE TITLE
Allow multiple prefixes for each workdir

### ISSUE THREAD

**Issue by david-caro** [lago-project/lago#148]
Something similar to:

    lago checkout $env  # select default env to act on
    lago --env myenv <command>  # explicitly select the env to act on

**Comment by ifireball** [comment]
+1

**Comment by ifireball** [comment]
I'd rather not have action words preceded with double dash, that is for
optional stuff imo.
maybe consider:

lago environment init foo myenv.json
lago environment destroy foo
lago environment list
lago environment use foo
lago environment [show-current]

and then "lago (init|destroy) --env=foo" is a syntactic sugar?



On 1 March 2016 at 19:04, David Caro <notifications@github.com> wrote:

> will need also some way to list the available environments:
> lago --list-envs
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lago-project/lago/issues/148#issuecomment-190816478>.
>



-- 
*Barak Korren*
bkorren@redhat.com
RHEV-CI Team

**Comment by david-caro** [comment]
Reworded the concepts:

  Workspace - base directory, contains prefixes
  Prefix - Directory with all the virtual resources and files needed to run a virtual environment

**Comment by david-caro** [comment]
So the new commands are:

    lago set-current <prefix-name>
    lago destroy --all-prefixes
    lago --workspace <path-to-workspace> <command>
    lago --prefix-name <name-of-prefix> <command>
    lago list envs|prefixes

The default prefix-name is 'default', and the default workspace is 'auto', what means that it will look for it (any .lago dir that is a workdir in $PWD or any if it's parents).

You can mix --workspace and --prefix-name too.

And the init command will create now workdirs instead of prefixes directly (that is, a directory with a current soft link and a prefix).

Of course, the old prefixes are still supported, but are not created anymore.

**Comment by ifireball** [comment]
what is a "workspace" as opposed to a "workdir"?

On 9 March 2016 at 20:20, David Caro <notifications@github.com> wrote:

> So the new commands are:
>
> lago set-current <prefix-name>
> lago destroy --all-prefixes
> lago --workspace <path-to-workspace> <command>
> lago --prefix-name <name-of-prefix> <command>
> lago list envs|prefixes
>
> The default prefix-name is 'default', and the default workspace is 'auto',
> what means that it will look for it (any .lago dir that is a workdir in
> $PWD or any if it's parents).
>
> You can mix --workspace and --prefix-name too.
>
> And the init command will create now workdirs instead of prefixes directly
> (that is, a directory with a current soft link and a prefix).
>
> Of course, the old prefixes are still supported, but are not created
> anymore.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lago-project/lago/issues/148#issuecomment-194435142>.
>



-- 
*Barak Korren*
bkorren@redhat.com
RHEV-CI Team

**Comment by david-caro** [comment]
my brain playing me a trick, s/workspace/workdir/
