### ISSUE TITLE
Add a way to export/import a full prefix

### ISSUE THREAD

**Issue by david-caro** [lago-project/lago#159]

**Comment by gbenhaim** [comment]
We want the ability to create and customize Lago env on one machine and then migrate this environment to another machine (maybe even store it on a central repo).

For example create an oVirt env, save, publish, and then a user can just pull and use it, without spending time on deployment and depending on yum repos.

Things that we need to take care of:

1. Choose the correct base images path.
2. Download the base image (if not already exist in the cache)
3. Allocate a new subnet.
4. Create a new uuid for the prefix.

Feel free to add your thoughts.

**Comment by nvgoldin** [comment]
one part of it is:https://github.com/lago-project/lago/issues/51, added some draft proposal there.

**Comment by nvgoldin** [comment]
done.
