### ISSUE TITLE
Add a default init file in the current dir when not specified

### ISSUE THREAD

**Issue by david-caro** [lago-project/lago#165]
For example $PWD/.lago.init or similar

**Comment by ifireball** [comment]
I don't think it should be hidden, maybe $PWD/Lagofile ? (Like Makefile,
Puppetfile, Gemfile)

On 7 March 2016 at 17:52, David Caro <notifications@github.com> wrote:

> For example $PWD/.lago.init or similar
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lago-project/lago/issues/165>.
>



-- 
*Barak Korren*
bkorren@redhat.com
RHEV-CI Team

**Comment by david-caro** [comment]
Finally decided for LagoInitFile
