### ISSUE TITLE
el7 images don't boot without any network defined

### ISSUE THREAD

**Issue by david-caro** [lago-project/lago#168]
After the lilo menu, they just hand on blank screen

**Comment by david-caro** [comment]
Sooorry, that's not true, it just takes more than usual

**Comment by ifireball** [comment]
Not sure which image you booted, but if it has cloud-init it may explain
the slowness.

On 8 March 2016 at 17:00, David Caro <notifications@github.com> wrote:

> Closed #168 <https://github.com/lago-project/lago/issues/168>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lago-project/lago/issues/168#event-581830323>.
>



-- 
*Barak Korren*
bkorren@redhat.com
RHEV-CI Team

**Comment by david-caro** [comment]
it's actually not that much slowness, but nothing is shown on the console so it feels like a lot of time. I used the el7-base image on the public lago repo

**Comment by david-caro** [comment]
I was not using the new el7-base, but centos7-host, the old one has no serial support, the new one work ok :smile:
