### ISSUE TITLE
domain names are too long

### ISSUE THREAD

**Issue by tlitovsk** [lago-project/lago#180]
in case of substantial domain names the contact to the guest engine is broken
The reason is that the file descriptor for it seats in /var/lib/libvirt/qemu/guest...../<domain-name>/qemu.guest.....

I this filename is longer then 48 chars its get truncated and cant be used

**Comment by david-caro** [comment]
Can you clarify a couple things here?

- What are you referring to with 'guest engine'?
- Who loses contact and what do you mean by contact?
- Who truncates the domain name?
- Which domain names are too long?
- In the path that you put as an example, I guess that the .... should be replaced by the domain name?

**Comment by david-caro** [comment]
hello?

**Comment by tlitovsk** [comment]
guest engine - the ovirt engine that  runs on a vm in the lago tests
Lago contacts the vms using qemu serial channel
If the domain name too long the qemu agent on the guest is not contacted.
yes its the domain name

**Comment by david-caro** [comment]
You mean in the ovirt-system-tests?
I have guest agent sockets with names like '5479d17c-lago_basic_suite_3_5_storage-iscsi.org.qemu.guest_agent.0' (67 chars) that are working ok. Which os are you running on?

**Comment by tlitovsk** [comment]
I run fedora 23 and I think you should also count the full path
And this name doesnt work for me

**Comment by david-caro** [comment]
I'm running fc23 too.
The full path is '/var/lib/libvirt/qemu/channel/target/5479d17c-lago_basic_suite_3_5_storage-iscsi.org.qemu.guest_agent.0' (104 chars) and that is working for me.

Can you be more specific of what is failing when? got a tracedump? something I can try to reproduce?

**Comment by tlitovsk** [comment]
Sure
I will make one
I see the guest.agent.0 filename gets truncated on the file system
And then lago cant connect to the qemu guest agent

**Comment by nvgoldin** [comment]
might be related to: https://bugzilla.redhat.com/show_bug.cgi?id=1289363
if that was the case(it should have been fixed by now), also this is a ticket to OST.
