### ISSUE TITLE
Lago destroy & cleanup doesn't remove network bridge created by tests

### ISSUE THREAD

**Issue by eedri** [lago-project/lago#198]
When running basic suite for 3.6, and test fail in the middle or there was a network error for some reason, lagocli cleanup or lagocli destroy doesn't remove network bridges (see attached image)
![screenshot from 2016-03-29 16-48-10](https://cloud.githubusercontent.com/assets/1614735/14110337/ddcd15b8-f5bd-11e5-847c-5abf15bb880a.png)

We should extend either of the commands if possible to remove anything created by running the tests

**Comment by david-caro** [comment]
On 03/29 06:53, Eyal Edri wrote:
> When running basic suite for 3.6, and test fail in the middle or there was a network error for some reason, lagocli cleanup or lagocli destroy doesn't remove network bridges (see attached image)
> ![screenshot from 2016-03-29 16-48-10](https://cloud.githubusercontent.com/assets/1614735/14110337/ddcd15b8-f5bd-11e5-847c-5abf15bb880a.png)
> 
> We should extend either of the commands if possible to remove anything created by running the tests

To cleanup a test run, use:

   ./run_suite.sh --cleanup <suite_name>

For example:

  ./run_suite.sh --cleanup basic_suite_3.6


Keep in mind that the patch https://gerrit.ovirt.org/#/c/5354 introduces some
fixes for the management of the new 'workspace' concept in lago.


> 
> 
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/lago-project/lago/issues/198

-- 
David Caro

Red Hat S.L.
Continuous Integration Engineer - EMEA ENG Virtualization R&D

Tel.: +420 532 294 605
Email: dcaro@redhat.com
IRC: dcaro|dcaroest@{freenode|oftc|redhat}
Web: www.redhat.com
RHT Global #: 82-62605

**Comment by eedri** [comment]
Can we add './run_suite.sh --cleanup basic_suite_3.6' to the cleanup section in the README?

http://lago.readthedocs.org/en/latest/README.html#cleanup

**Comment by david-caro** [comment]
On 03/29 07:33, Eyal Edri wrote:
> Can we add './run_suite.sh --cleanup basic_suite_3.6' to the cleanup section in the README?

Sure, though I think that should not be explained there, but on
ovirt-system-tests own repo and docs.

The run_suite script is not part of lago.

> 
> http://lago.readthedocs.org/en/latest/README.html#cleanup
> 
> ---
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/lago-project/lago/issues/198#issuecomment-202923377

-- 
David Caro

Red Hat S.L.
Continuous Integration Engineer - EMEA ENG Virtualization R&D

Tel.: +420 532 294 605
Email: dcaro@redhat.com
IRC: dcaro|dcaroest@{freenode|oftc|redhat}
Web: www.redhat.com
RHT Global #: 82-62605

**Comment by eedri** [comment]
Agree, but as long as we don't replace the example run of Lago with something else that is not relevant for ovirt-system-tests, we need to provide all the tools to whoever tries to run Lago to be able to handle any issue he/she encounter

Once we can put a different example of basic install, we need to provide any info that is relevant.
this is something @gbenhaim can do as a task.

+1 for creating an ovirt-system-tests documentation, I'm planning on sending initial doc to ovirt.org site soon..

**Comment by david-caro** [comment]
@eedri If you followed the readme, the last cleanup should have removed the vms and the networks, do you have the stderr and stdout arround?

**Comment by nvgoldin** [comment]
@eedri - is this still relevant? closing for now.
