### ISSUE TITLE
Automate the configuration process when installing Lago

### ISSUE THREAD

**Issue by gbenhaim** [lago-project/lago#212]
All the configuration that need to be done to the users
machine should be applied automatically when installing Lagos rpm.

**Comment by david-caro** [comment]
If you are installing it right now and having issues, can you provide a list of what is missing?

David Caro

El 11/4/2016 13:09, Gal Ben Haim <notifications@github.com> escribió:

All the configuration that need to be done to the users
machine should be applied automatically when installing lagos rpm.
