### ISSUE TITLE
add reposync dir to deault lago.conf file 

### ISSUE THREAD

**Issue by eedri** [lago-project/lago#215]
When you install lago, the reposync dir is put in /var/lib/lago, but it doesn't appear in /etc/lago.d/lago.conf as config option you can change, similiar to repos and store.

the default lago.conf file should include it and allow updating the path.

e.g:

reposync_dir = /var/lib/lago/reposync

**Comment by david-caro** [comment]
Depends on: #58

**Comment by nvgoldin** [comment]
done in https://github.com/lago-project/lago/issues/324
