### ISSUE TITLE
We should ensure our lago-images created images are created with 'preallocation=metadata'.

### ISSUE THREAD

**Issue by david-caro** [lago-project/lago#254]

**Comment by david-caro** [comment]
It's not supported for layer images, only for the root image

**Comment by mykaul** [comment]
I've sent a question to libguestfs mailing list to ask how we virt-builder can be configured to support this.

**Comment by mykaul** [comment]
1. virt-builder is already using preallocation=metadata if the format is qcow2.
2. Small patch to prefix.py can do it for our own qcow2 created files - will send a patch.

**Comment by david-caro** [comment]
The merge pipeline failed, so I was able to update the patch with your comments :)
