### ISSUE TITLE
Add virt-provider tag to domains schema

### ISSUE THREAD

**Issue by lveyde** [lago-project/lago#256]
Add virt-provider tag should be added to support creation hosts as VMs/containers using additional providers i.e. RHEV/oVirt, Docker etc.

It will also allow creation of virtual domains (hosts), e.g. where Lago needs only to be aware of the host and it's parameters i.e. IP or MAC address, and this in order to be able to provide a mapping between a hostname and it's IP, update DHCP (in case it's being managed by Lago) with this info etc., but doesn't need to create a VM/container by itself.

**Comment by gbenhaim** [comment]
'vm-provider' key was added to the init file.
