### ISSUE TITLE
Support partial static IP definition in prefix schema

### ISSUE THREAD

**Issue by lveyde** [lago-project/lago#257]
In case of NAT network we can't know the full IP address which can be assigned to domain (host).
That is because we don't know which IP subnet will be used by the domains, until one is assigned.

Thus if we want to assign static IPs we need to support a partial definition, e.g. to assign .10 or .99, which will be translated at the time of the network creation to the correct subnet e.g. 192.168.200.10 or 192.168.205.99.

**Comment by gbenhaim** [comment]
This feature is supported.
For each vm that you want to assign a static ip, you should add an
entry <ip: adress> in the init file. Note that only the last octet will be taken from this entry, and then
Lago will add it to the subnet that was chosen.
It means that the first 3 octets doesn't have a meaning. Here is an example:

`       
 "vm0-server": {
            "memory": "1024",
            "nics": [
                {
                    "net": "lago",
                    "ip": "999.999.999.150"
                }
             add another configurations here....
}
`
