### ISSUE TITLE
repo setup issue 

### ISSUE THREAD

**Issue by irosenzw** [lago-project/lago#273]
While running repo setup stage on an environment that contain pre-installed iso (qcow2),  the repo setup fails. It doesn't recognize the qcow2 disto, so it saves it as 'None' along with all the distros it does recognize.

the problem occurs in  Ovirtlago -> \__init\__.py -> def prepare_repo

My suggestion is to add this line:
all_dists = filter(lambda dist: dist is not None, all_dists)

After the line:
all_dists = list(set(engine_dists + vdsm_dists))

**Comment by david-caro** [comment]
you can work around it by adding the 'distro' entry to the domain definition with the current distro.

What is the reposetup command error?

**Comment by irosenzw** [comment]
The work around is working fine. Although I think it will be wise to fix that anyway in case the user didn't define a distro in the LagoInitFile. 

![repo-setup error](https://cloud.githubusercontent.com/assets/18301938/15734799/dce53d36-289b-11e6-8b92-6a2056156f8a.png)

**Comment by david-caro** [comment]
totally agree :+1:

**Comment by gbenhaim** [comment]
The distro field is being used when building the internal repo.
The rpms will be added from the reposync directory to the internal repo only if the suffix
of the repo name is equal to 'distro'.
This approach prevents waste of time on adding rpms that are in the reposync directory, but 
aren't needed to the current session of lago.

So, even when working with custom images, if you want to use reposync, the distro must be specified in the init file.
