### ISSUE TITLE
Unexpected output during dnf update + rpm install shouldn't mess with my firewall

### ISSUE THREAD

**Issue by sandrobonazzola** [lago-project/lago#292]
While running dnf update:

python-lago-ovirt-0.23.0-1.fc23.noarch                                                         5/54 
success
Warning: ALREADY_ENABLED: ovirtlago
success

lago-0.19.0-1.fc23.noarch                                                                     29/54 
success
success

rpm install / update shouldn't write any extra output.
Looking at spec file I see that in %post and %preun firewalld commands are issued.
Please remove them, rpm shouldn't assume that firewalld is available and shouldn't mess with firewall configuration.

**Comment by david-caro** [comment]
#45
