### ISSUE TITLE
Bug 1294653 - (v0.5) ovirtlago assertion check should sleep between retries 

### ISSUE THREAD

**Issue by eedri** [lago-project/lago#3]
Description of problem:
Currently the code @ ovirtlago/testlib.py is:
143 def assert_true_within(func, timeout):
144     with utils.EggTimer(timeout) as timer:
145         while not timer.elapsed():
146             try:
147                 if func():
148                     return
149             except Exception:
150                 pass
151     raise AssertionError('Timed out')

Specifically, there is a tight loop there, which consumes CPU needlessly - occupying both the client and the target of func() (for example, checking something on the engine).

Simple patch:

23 import time
...

144 def assert_true_within(func, timeout):
145     with utils.EggTimer(timeout) as timer:
146         while not timer.elapsed():
147             try:
148                 if func():
149                     return
150                 time.sleep(1)
151             except Exception:
152                 pass
153     raise AssertionError('Timed out')

solves this, by adding a 1 sec. sleep between retries (practically, can even extend to 3 or 5 seconds).

Version-Release number of selected component (if applicable):
0.5
Collapse All Comments

Migrated from: https://bugzilla.redhat.com/show_bug.cgi?id=1294653

**Comment by mykaul** [comment]
Already fixed, can be closed.
