### ISSUE TITLE
Installing Lago on Fedora 21 from repo doesn't create executable in any /bin directory

### ISSUE THREAD

**Issue by kivio** [lago-project/lago#305]
After installing Lago based on adding repo for fedora 21 and using yum install command executable is not copied to any `/bin` directory. When i do that this same way on Centos 7.2 all is okay.

Only command from lago that is available on this fedora is `lagocli`.

**Comment by kivio** [comment]
There is information about installed version:

```
kivio@localhost ~> yum info lago
Loaded plugins: langpacks
Installed Packages
Name        : lago
Arch        : noarch
Version     : 0.4
Release     : 0.4.fc21
Size        : 66 k
Repo        : installed
From repo   : lago
```

**Comment by mykaul** [comment]
This is a very old Lago release - and F21 is certainly not supported anymore. Can you try on F23 or F24, with a recent Lago release?

**Comment by kivio** [comment]
Ok, it's no problem it works for me on Centos. Maybe one thing, that information about supported versions of systems can be described on github page.

**Comment by eedri** [comment]
I'm not sure we need to specify that an EOL fedora is not supported, we'll need to update this documentation every 6 months on a fedora release.

I think its reasonable to assume EOL versions are not supported. (fc21 & fc22 in this case)
