### ISSUE TITLE
Remote repository synchronization should be more reliable

### ISSUE THREAD

**Issue by sandrobonazzola** [lago-project/lago#319]
Remote repository synchronization should be more reliable.
In the following logs from http://jenkins.ovirt.org/job/vdsm_4.0_check-merged-fc23-x86_64/146/console 
- It says that a first reposync run completed with success.
- It then advise that sometime reposync fails and try again but previous sync succeeded.
- It resync and finsih with success.
- It the says it failed and it tries again.
- It says it finished with success and then fail again.

the repository synchronization should be more reiliable and use all available mirrors.

`0:06:53.074   # Syncing remote repos locally (this might take some time): 
00:06:53.074     \* Acquiring lock for /var/lib/lago/reposync/repolock: 
00:06:53.075     \* Acquiring lock for /var/lib/lago/reposync/repolock: Success (in 0:00:00)
00:06:53.077     \* Running reposync: 
00:06:58.904     \* Running reposync: Success (in 0:00:05)
00:06:58.905     \* Due to bug https://bugzilla.redhat.com/show_bug.cgi?id=1332441 sometimes reposync fails to update some packages that have older versions already downloaded, will remove those if any and retry
00:06:59.019     \* Rerunning reposync: 
00:06:59.839     \* Rerunning reposync: Success (in 0:00:00)
00:06:59.840     \* Failed to run reposync again, that usually means that some of the local rpms might be corrupted or the metadata invalid, cleaning caches and retrying a second time
00:06:59.896     \* Rerunning reposync a last time: 
00:07:00.837     \* Rerunning reposync a last time: Success (in 0:00:00)
00:07:00.838     \* reposync command failed with following output: 
local-vdsm-build-fc23                                       | 2.9 kB  00:00  
00:07:00.839 
local-vdsm-build-fc23/primary_db                            |  17 kB  00:00  
00:07:00.839 
ovirt-4.0-snapshot-fc23                                     | 2.9 kB  00:00  
00:07:00.839 
ovirt-4.0-snapshot-fc23/primary_db                          |  95 kB  00:00  
00:07:00.840 
ovirt-4.0-snapshot-static-fc23                              | 2.9 kB  00:00  
00:07:00.840 
ovirt-4.0-snapshot-static-fc23/primary_db                   | 8.0 kB  00:00  
00:07:00.840 
ovirt-release40-4.0.0-1.noarch FAILED  
00:07:00.840 
(1/3): ovirt-release40-4.0. 0% [                 ]  0.0 B/s |    0 B  --:-- ETA 

ovirt-release40-snapshot-4.0.0 FAILED  
00:07:00.841 
(1/3): ovirt-release40-pre- 0% [                 ]  0.0 B/s |    0 B  --:-- ETA 

ovirt-release40-pre-4.0.0-1.no FAILED  
00:07:00.841 
(1/3): ovirt-release40-pre- 0% [                 ]  0.0 B/s |    0 B  --:-- ETA 
ovirt-release40-snapshot-4.0.5-0.0.master.20160912021832.git32a9727.noarch: [Errno 256] No more mirrors to try.
00:07:00.842 ovirt-release40-4.0.5-0.0.master.20160912021832.git32a9727.noarch: [Errno 256] No more mirrors to try.
00:07:00.842 ovirt-release40-pre-4.0.5-0.0.master.20160912021832.git32a9727.noarch: [Errno 256] No more mirrors to try.
00:07:00.842 
00:07:00.842 and following error: 
00:07:00.842 Yum-utils package has been deprecated, use dnf instead.
00:07:00.843 See 'man yum2dnf' for more information.
`

**Comment by eedri** [comment]
@gbenhaim is this implemented in the lago-ovirt plugin or part of ovirt-system-tests?
