### ISSUE TITLE
From time to time the ci jobs fail with 'lmonitor socket did not show up: No such file or directory'

### ISSUE THREAD

**Issue by david-caro** [lago-project/lago#32]
Find out how to alleviate the issue until libvirt addresses the problem on their side

Moved from https://bugzilla.redhat.com/show_bug.cgi?id=1287260

Description of problem:
> Sometimes the ci jobs fail to run the functional tests when doing the prefix startup, and they fail with:

    19:15:08 not ok 8 basic.full_run: start everything at once
    19:15:08 # (from function `helpers.equals' in file tests/functional/helpers.bash, line 49,
    19:15:08 #  in test file tests/functional/basic.bats, line 126)
    19:15:08 #   `helpers.equals "$status" '0'' failed
    19:15:08 # RUNNING:lagocli start
    19:15:08 # WARNING: current session does not belong to lago group.
    19:15:08 # 2015-12-01 19:14:13,413 - root - INFO - Creating network lago_functional_tests
    19:15:08 # 2015-12-01 19:14:17,934 - root - INFO - Starting VM lago_functional_tests_vm01
    19:15:08 # libvirt: QEMU Driver error : monitor socket did not show up: No such file or directory
    19:15:08 # 2015-12-01 19:15:04,689 - root - INFO - Destroying network lago_functional_tests
    19:15:08 # 2015-12-01 19:15:08,351 - root - ERROR - Error occured, aborting
    19:15:08 # Traceback (most recent call last):
    19:15:08 #   File "/usr/bin/lagocli", line 528, in main
    19:15:08 #     func(args)
    19:15:08 #   File "/usr/bin/lagocli", line 85, in wrapper
    19:15:08 #     return func(lago.Prefix(os.getcwd()), args)
    19:15:08 #   File "/usr/bin/lagocli", line 93, in wrapper
    19:15:08 #     return func(prefix, args)
    19:15:08 #   File "/usr/bin/lagocli", line 106, in do_start
    19:15:08 #     prefix.start()
    19:15:08 #   File "/usr/lib/python2.7/site-packages/lago/__init__.py", line 594, in start
    19:15:08 #     self.virt_env.start()
    19:15:08 #   File "/usr/lib/python2.7/site-packages/lago/virt.py", line 138, in start
    19:15:08 #     vm.start()
    19:15:08 #   File "/usr/lib/python2.7/site-packages/lago/virt.py", line 756, in start
    19:15:08 #     self._env.libvirt_con.createXML(self._libvirt_xml())
    19:15:08 #   File "/usr/lib64/python2.7/site-packages/libvirt.py", line 3611, in createXML
    19:15:08 #     if ret is None:raise libvirtError('virDomainCreateXML() failed', conn=self)
    19:15:08 # libvirtError: monitor socket did not show up: No such file or directory
    19:15:08 # 1 == 0

David Caro 2016-01-26 04:37:55 EST
> This seems to be an issue in libvirt, that is not able to create the per-user socket fast enough (or the client does not wait enough time for it to appear), see https://bugzilla.redhat.com/show_bug.cgi?id=1301391

**Comment by mykaul** [comment]
But https://bugzilla.redhat.com/show_bug.cgi?id=1271183 is already fixed, why do we need this?

**Comment by david-caro** [comment]
Because on ovirt infra jenkins, most of the slaves don't have that fix, and it's way simpler to fix it here, that wait until everything is upgraded there (though it's on the works, it will take some time).

**Comment by mykaul** [comment]
@david-caro - I don't like this approach - we are adding complexity to our code, for a bug in a different component, that could be solved easily with up-to-date infra.

**Comment by david-caro** [comment]
Agree that it's not nice code, but the problem is that is not 'easy' to keep an up-to-date infra, and this is happening now more than 1 out of each 3 runs, practically blocking any release.

I can manually update all the fedora slaves, though that will take me some time (way more than it took to create this fix), will create load on the slaves, and will most probably interfere with other projects jobs. It's also a one-time solution.

Should I try that second approach?

**Comment by mykaul** [comment]
Isn't that why we have Puppet on our Infra? Exactly to ensure clean, accurate deployment?
But yes, I think it's important to upgrade.

**Comment by david-caro** [comment]
It's not that simple, puppet 3 on fc23 was not working until last week (and the package we are using is a custom one). And the new puppet 4 is not yet supported by foreman (will be in the nexw 1.12 release iirc).

Machines are not regenerated on each run, as no solution to automatically generate the template or refresh the vms was implemented yet, so they drag all the base os from the original install (made quite long time ago), and telling puppet to upgrade everything is very very risky (and it might interfere with jenkins builds, as you can't coordinate the puppet run, with the current setup).

I'll manually update the vms one making sure they are not running any jobs while doing it.
