### ISSUE TITLE
prefix.py - "name" key is declared twice with different values

### ISSUE THREAD

**Issue by mykaul** [lago-project/lago#321]
7b940c22 lib/lago/prefix.py (David Caro     2016-02-24 17:10:19 +0100  745)                           "name": "root",
7b940c22 lib/lago/prefix.py (David Caro     2016-02-24 17:10:19 +0100  746)                           "name": os.path.basename(image_file),

and indeed, 'make check' is unhappy:

./lago/prefix.py:745:27: F999 dictionary key 'name' repeated with different values
./lago/prefix.py:746:27: F999 dictionary key 'name' repeated with different values
Makefile:54: recipe for target 'check-local' failed

**Comment by david-caro** [comment]
It actually comes from another commit (that one only changes the file path), they actually come from two different comits:

4cbca73d lib/lago/__init__.py    (Tolik Litovsky 2016-02-02 13:08:02 +0200 648)                           "name": "root",
b09cbd3b lib/lago/__init__.py    (Tolik Litovsky 2016-01-21 15:12:09 +0200 649)                           "name": os.path.basename(image_file),
