### ISSUE TITLE
3.6 engine fails setup because of wrong answer in the answer file

### ISSUE THREAD

**Issue by mykaul** [lago-project/lago#34]
Seems like I'm suffering from https://bugzilla.redhat.com/show_bug.cgi?id=1149904 :

In basic_suite_3.6/engine-answer-file.conf  , the value
OSETUP_RPMDISTRO/enableUpgrade=none:None
Should be:
OSETUP_RPMDISTRO/enableUpgrade=bool:False

I'm not sure how it did not bother me before today!

**Comment by mykaul** [comment]
Sent https://gerrit.ovirt.org/#/c/52749/ to fix this.

**Comment by david-caro** [comment]
yep, that's not lago itself, but ovirt system tests issue
