### ISSUE TITLE
[Docs] Requirement for EPEL is missing in the docs

### ISSUE THREAD

**Issue by dyasny** [lago-project/lago#353]
`yum install python-lago lago` fails on dependencies, unless EPEL is enabled

tested on RHEL 7.2

Docs link: http://lago.readthedocs.io/en/stable/Installation.html#installing-the-packages

**Comment by nvgoldin** [comment]
Thanks for reporting. This is already updated in http://lago.readthedocs.io/en/0.27/Installation.html, but the 'stable' docs still point to 0.26, not sure when it is 'auto-updated'. @dcaro - you know?

**Comment by nvgoldin** [comment]
looks like it is updated now, probably a time-trigger.

**Comment by david-caro** [comment]
@nvgoldin hey, my nick is @david-caro ;), for the versions in the docs, I thnik it's related to the 'stable' vs 'latest' links, looking.

**Comment by david-caro** [comment]
I've deactivated the latest one leaving only the 'stable' one. I don't see anything I can play with to investigate further but yep, maybe it takes a bit of extra time to update the latest link once the version is updated :/

**Comment by david-caro** [comment]
Btw. @nvgoldin let me know if you don't have access to the readthedocs project and I'll give you access, though iirc there was some generic account that should have access.
