### ISSUE TITLE
ability to choose version

### ISSUE THREAD

**Issue by pkliczewski** [lago-project/lago#355]
We need to be able to specify which version should be tested. Without this functionality it is hard to say what we are testing.

**Comment by nvgoldin** [comment]
Hi @pkliczewski, which version are you referring to? the image? (the suite from OST?) lago's?

**Comment by pkliczewski** [comment]
@nvgoldin I would like to be able to specify which version of engine, vdsm or jsonrpc is used during single run.

I had a situation when I run lago on my machine and I used custom repo with my changes. During several runs there was new version available which was tested instead in follow up runs.

I saw similar issue in CI where I thought I am testing specific version but based on the logs I saw that it was different.

**Comment by nvgoldin** [comment]
thanks, lets continue the discussion on https://ovirt-jira.atlassian.net/browse/OVIRT-763, as this is OST related.
