### ISSUE TITLE
Move reposync feature from ovirt-lago to Lago

### ISSUE THREAD

**Issue by gbenhaim** [lago-project/lago#363]
1. This feature could be useful for non ovirt users, thus should be in lago.
2. We need to figure out how to implement reposync in system which are not el based.

**Comment by nvgoldin** [comment]
part of https://github.com/lago-project/lago/issues/350

**Comment by eedri** [comment]
if we're already splitting the repo to ost-lago-plugin as described in #350, might be better to move reposync there rather than incorporating as lago core feature.

**Comment by gbenhaim** [comment]
I don't think that this one is needed anymore.
