### ISSUE TITLE
on hosts with firewalld, when updating lago, the 'ovirtlago' service is dropped

### ISSUE THREAD

**Issue by nvgoldin** [lago-project/lago#380]
quick workaround:
```
sudo firewall-cmd --add-service=ovirtlago --permanent
sudo firewall-cmd --reload
```

side-note: this should move to the ost-plugin but until that happens it needs to be fixed.

**Comment by nvgoldin** [comment]
Might came across the reason, quoting from http://www.ibm.com/developerworks/library/l-rpm2/:
```quote
Hence, the order of operations during an upgrade is:
    Run the %pre section of the RPM being installed.
    Install the files that the RPM provides.
    Run the %post section of the RPM.
    Run the %preun of the old package.
    Delete any old files not overwritten by the newer version. (This step deletes files that the new package does not require.)
    Run the %postun hook of the old package.
```


And we have in lago.spec:
```
%preun  -n python-%{name}-ovirt
if which firewall-cmd &>/dev/null; then
    firewall-cmd --permanent --zone=public --remove-service=ovirtlago
    firewall-cmd --reload
fi
```
So basically the spec file adds the firewall-cmd rule and then in ``%preun``(of the old package) it removes it while running  'yum update'.

**Comment by ifireball** [comment]
And we have in lago.spec:

> %preun  -n python-%{name}-ovirt
> if which firewall-cmd &>/dev/null; then
>     firewall-cmd --permanent --zone=public --remove-service=ovirtlago
>     firewall-cmd --reload
> fi
>
> So basically the spec file adds the firewall-cmd rule and then in %preun(of
> the old package) it removes it while running 'yum update'.
>

There used to be a way to know during '%preun' if you were removing the
package or just running during upgrade. Check scripts for other packages
you will probably find someone using it.

Then again, we should probably just move all this logic to 'lago ovirt
serve' to be resilient to local user changes.
We should also make the firewall setting more secure by dynamically
creating a prefix-specific firewalld zone with the port open and routing
only the prefix networks into it.

-- 
Barak Korren
bkorren@redhat.com
RHCE, RHCi, RHV-DevOps Team
https://ifireball.wordpress.com/

**Comment by nvgoldin** [comment]
fixed
