### ISSUE TITLE
functional tests became extremely slow on el7 and fail CI

### ISSUE THREAD

**Issue by nvgoldin** [lago-project/lago#389]
happens locally and:

http://jenkins.ovirt.org/job/lago_master_check-patch-el7-x86_64/417/
http://jenkins.ovirt.org/job/lago_master_check-patch-el7-x86_64/416/

**Comment by nvgoldin** [comment]
I am guessing it is related to CentOS 7.3 being pushed and misbehaving new packages under mock.

**Comment by nvgoldin** [comment]
So the root cause is that under mock(might be in 7.3 in general) virt-sysprep is stuck on:
```
4 0
SeaBIOS (version 1.9.1-5.el7)
Booting from ROM...
Probing EDD (edd=off to disable)... 
```
adding ``export LIBGUESTFS_APPEND=edd=off`` resolves the issue, still testing if this is mock specific.

**Comment by nvgoldin** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1404287

**Comment by ifireball** [comment]
Looking at the logs you've places in the bug report - it seems you are not using qemu-kvm-ev. Why is that?

**Comment by nvgoldin** [comment]
@ifireball  - Good point to check what we install under mock. In the bugzilla - I wanted to check the bug is reproducible on "plain" CentOS 7.3 VM taken directly from virt-builder after executing ``yum install libguestfs-tools``.

**Comment by nvgoldin** [comment]
fixed by https://github.com/lago-project/lago/issues/391
