### ISSUE TITLE
Make reposync parallel and clear cache in the same stage of removing conflicting RPMs

### ISSUE THREAD

**Issue by nvgoldin** [lago-project/lago#393]
After https://github.com/lago-project/lago/pull/369(and its fix https://github.com/lago-project/lago/pull/374) were merged - reposync runs per repo. We can make it run in parallel, each repo on a different thread. Some care needs to be taken when clearing the cache(currently it clears the global cache).

Also - after removing conflicting RPMs we can already clean the cache as it is already corrupted, this could save the third run.

**Comment by mykaul** [comment]
I'm wondering about locks. (is there a difference between running multiple reposync commands with a single repo each to running a single reposync with multiple repos?)

**Comment by nvgoldin** [comment]
As far as I can tell, yes: if passing multiple repositories, it first determines what needs to be downloaded from all repositories and then calls url-grabber on the entire list.

So actually running multiple reposync commands could be faster. Also, if one repo fail, we only re-run reposync for that repo instead of parsing the entire list again. I think the cache is per-repo also(ATM it is in /var/lib/lago/reposync/cache/repo-name), so unless there is some other hidden cache it uses(like yum's) it should be safe to remove only that cache directory.

**Comment by gbenhaim** [comment]
We use a tempdir for the cache - it doesn't cost a lot of time and reduced errors significantly.
We can discuss parallel reposync in https://github.com/lago-project/lago-ost-plugin/issues/42
