### ISSUE TITLE
Enhance Unit Testing

### ISSUE THREAD

**Issue by gbenhaim** [lago-project/lago#394]
We need to enhance the unit tests.
In order to do so we need to invest some effort on creating proper "Stabs" e.g:
1. VM object
2. virt env
3. spec file
4. etc...

**Comment by ifireball** [comment]
Too many stubs is a tests design smell, read about the Python 'mock' library.

**Comment by mykaul** [comment]
I don't think more unit test for a testing framework makes it much better.
Real use case in the field makes it better.

**Comment by nvgoldin** [comment]
I think we had some progress here, at least with the new features. As we probably aren't going to invest time solely in this, but rather add tests for each new feature, I'm closing this for now.
