### ISSUE TITLE
Bug 1294625 - (v0.5) Lago uses a pre-defined Storage with OVF_STORE disks (should probably build one?)

### ISSUE THREAD

**Issue by eedri** [lago-project/lago#4]
Description of problem:

See https://bugzilla.redhat.com/show_bug.cgi?id=1218151#c3 for specific details.

Version-Release number of selected component (if applicable):
0.5

How reproducible:
Sometimes?

Migrated from: https://bugzilla.redhat.com/show_bug.cgi?id=1294625

**Comment by david-caro** [comment]
This is not lago issue but ovirt-system-tests

**Comment by eedri** [comment]
I reopened https://bugzilla.redhat.com/show_bug.cgi?id=1294625.
closing this one.
