### ISSUE TITLE
libvirt_username and libvirt_password are missing in lago.conf

### ISSUE THREAD

**Issue by mpolednik** [lago-project/lago#413]
Before config was generated, these values were present to allow for setting libvirt sasl auth. Now they are missing and have to be added manually.

**Comment by nvgoldin** [comment]
@mpolednik, they are available if you run ``lago generate-config --verbose``, all variables that do not have defaults aren't displayed when running without  ``--verbose``. The ``lago.conf`` is auto-generated in the .spec file by running ``lago generate-config``, so that explains why its not there.

**Comment by nvgoldin** [comment]
@mpolednik  - I'm closing this for now, if you think it still needs discussion, please reopen.
