### ISSUE TITLE
ovirtlago: rotate logs between tests

### ISSUE THREAD

**Issue by nvgoldin** [lago-project/lago#420]
Now that we collect the entire '/var/log' directory in ost-plugin, it would be that on each 'runtest' command we would only collect the logs per that test, instead of repeatedly collecting the entire directory. This will also reduce the size of the collected logs.

**Comment by gbenhaim** [comment]
moved to lago-ost-plugin https://github.com/lago-project/lago-ost-plugin/issues/38
