### ISSUE TITLE
Lago uses custom build of python-setuptools-18.0.1-2.el7.centos.noarch

### ISSUE THREAD

**Issue by gbenhaim** [lago-project/lago#468]
Lago uses a custom build of ```python-setuptools-18.0.1-2.el7.centos.noarch``` taken from ```http://resources.ovirt.org/repos/ci-tools/el7/noarch/```.

We need to check what is the reason for using this version, and then justify the use of it. If this custom package isn't needed anymore, we should stop use it.

**Comment by nvgoldin** [comment]
@david-caro  - you happen to remember what was the reason behind it? :)

**Comment by nvgoldin** [comment]
@gbenhaim  - https://bugzilla.redhat.com/show_bug.cgi?id=1389942, maybe comment there about what is missing in current ``python-setuptools`` from EPEL, with little luck they might backport it.
