### ISSUE TITLE
vm.py's defined() function is looking if a domain is defined, not if it's running

### ISSUE THREAD

**Issue by mykaul** [lago-project/lago#492]
Code:
```
    def defined(self):
        dom_names = [dom.name() for dom in self.libvirt_con.listAllDomains()]
        return self._libvirt_name() in dom_names
````

1. It's inefficient - you want to look for a specific domain, do it using lookup
2. It's not checking if it's running, but if it's defined (currently, we don't have persistent domains, but we could have).

See http://libvirt.org/docs/libvirt-appdev-guide-python/en-US/html/libvirt_application_development_guide_using_python-Guest_Domains-Information-IsActive.html for example.

**Comment by gbenhaim** [comment]
2 was fixed in https://github.com/lago-project/lago/pull/711
