### ISSUE TITLE
Bug 1294624 - (v0.5) Lago uses 4vCPUs by default - which is too much on lower end hosts 

### ISSUE THREAD

**Issue by eedri** [lago-project/lago#5]
Description of problem:
There's no value in running the hosts, the storage with 4 vCPUs. Especially on my low end hosts, it may cause CPU contention.

Version-Release number of selected component (if applicable):
0.5

Additional info:
Change /usr/lib/ptrhon2.7/site-packages/lago/virt.py :
 682             '@VCPU@': self._spec.get('vcpu', 4),
 683             '@CPU@': self._spec.get('cpu', 4),

to:
 682             '@VCPU@': self._spec.get('vcpu', 2),
 683             '@CPU@': self._spec.get('cpu', 2),

Should fix that.

Migrated from: https://bugzilla.redhat.com/show_bug.cgi?id=1294624

**Comment by eedri** [comment]
Patch proposed: https://gerrit.ovirt.org/#/c/52536/

**Comment by mykaul** [comment]
Already fixed, can be closed.
