### ISSUE TITLE
Need to depend on python-netaddr

### ISSUE THREAD

**Issue by mykaul** [lago-project/lago#523]
Since some ovirt-system-tests use it, if it's not there, they fail.
I agree it's not Lago specific, but I don't think today there is another mean to deliver those deps (unless we package ovirt-system-tests in a RPM).

Saw when upgrading from Lago 0.33 to 0.37 and latest ovirt-system-tests. 
Tests that @lenoch added use it.

**Comment by eedri** [comment]
If indeed it's needed, then it will make sense to add it as dep to lago-ovirt ( soon to be lago-ost-plugin )

**Comment by lenoch** [comment]
I indeed added `python-netaddr` (in `automation/*.packages`). The library is useful for rich and non-NIH work with MACs and IPs, and as I am moving master suite network tests to SDKv4, I will use it more commonly.

I agree it's a good idea to add it as a dependency. My vote is on adding it as Eyal says.

**Comment by nvgoldin** [comment]
Sorry, I disagree here. If this is a depedency of the tests in OST it should be placed there. For OST(CI) this is not a problem, it can just be added to the .packages file, further it must be added there so we could track the dependencies. 
For none-CI runs, there are few possible solutions here:
1. Use @danielBelenky  new added feature to 'run_suite.sh': https://gerrit.ovirt.org/#/c/74835/, ```./run_suite.sh --local-rpms <package>``` which will install this RPM before the tests.
2. Add a ``requirements.txt`` file to OST, and add to ``run_suite.sh`` ``pip install -r requirements.txt`` before the run, or tell in the help message to do so.

Personally I favour (2).

With all that being said, I don't mind adding it for this specific library, as by coincidence last week I wanted to replace some of the "hand-crafted" logic in ``lago/subnet.py`` with netaddr, so sort of +1 from me to add it. Though as I wrote we must also solve it in OST - we cannot relay that OST by coincidence uses packages that Lago depends on. It needs its own dependency list.

**Comment by ifireball** [comment]
On 27 April 2017 at 10:12, Nadav Goldin <notifications@github.com> wrote:

> Sorry, I disagree here. If this is a depedency of the tests in OST it
> should be placed there. For OST(CI) this is not a problem, it can just be
> added to the .packages file, further it must be added there so we could
> track the dependencies.
> For none-CI runs, there are few possible solutions here:
>
>    1. Use @danielBelenky <https://github.com/danielBelenky> new added
>    feature to 'run_suite.sh': https://gerrit.ovirt.org/#/c/74835/, ./run_suite.sh
>    --local-rpms <package> which will install this RPM before the tests.
>    2. Add a requirements.txt file to OST, and add to run_suite.sh pip
>    install -r requirements.txt before the run, or tell in the help
>    message to do so.
>
> Personally I favour (2).
>
> With all that being said, I don't mind adding it for this specific
> library, as by coincidence last week I wanted to replace some of the
> "hand-crafted" logic in lago/subnet.py with netaddr, so sort of +1 from
> me to add it. Though as I wrote we must also solve it in OST - we cannot
> relay that OST by coincidence uses packages that Lago depends on. It needs
> its own dependency list.
>

I agree with Nadav, but am more in favour of #1. *.packages is a part of
standard-CI and is used throughout oVirt. It is already used at least by
vdsm devs as the source of truth about packages needed for testing env. I
don't see why use something else.

pip should only ever be used is the last resort for unpackaged dependencies
or versions, otherwise people tent to try and run it is root and end up
breaking their systems. If something like that must be used, then it is
preferable to use something like tox that also brings virtualenvs to the
mix.

-- 
Barak Korren
RHV DevOps team , RHCE, RHCi
Red Hat EMEA
redhat.com | TRIED. TESTED. TRUSTED. | redhat.com/trusted
