### ISSUE TITLE
hosts cpu set by image build

### ISSUE THREAD

**Issue by dron1** [lago-project/lago#548]
I created a new image on http://jenkins.ovirt.org/view/oVirt%20system%20tests/job/ovirt-system-tests_manual/ and was trying to use the image to run lago on my local machine. 
when I ran 'lago init' the vms failed to activate the hosts: 

  # Activating Engine Hosts: ERROR (in 0:00:57)
@ Starting oVirt environment: ERROR (in 0:00:58)
Error occured, aborting
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ovirtlago/cmd.py", line 360, in do_run
    self.cli_plugins[args.ovirtverb].do_run(args)
  File "/usr/lib/python2.7/site-packages/lago/plugins/cli.py", line 184, in do_run
    self._do_run(**vars(args))
  File "/usr/lib/python2.7/site-packages/lago/utils.py", line 501, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/lago/utils.py", line 512, in wrapper
    return func(*args, prefix=prefix, **kwargs)
  File "/usr/lib/python2.7/site-packages/ovirtlago/cmd.py", line 254, in do_ovirt_start
    prefix.virt_env.engine_vm().start_all_hosts(timeout=5 * 60)
  File "/usr/lib/python2.7/site-packages/ovirtlago/utils.py", line 145, in wrapped_func
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/ovirtlago/virt.py", line 414, in start_all_hosts
    api = self.get_api_v4(check=True)
  File "/usr/lib/python2.7/site-packages/ovirtlago/virt.py", line 302, in get_api_v4
    self._api_v4 = self._get_api(api_ver=4)
  File "/usr/lib/python2.7/site-packages/ovirtlago/virt.py", line 282, in _get_api
    raise RuntimeError('test api call failed')
RuntimeError: test api call failed

looking further at the reason I can see it's a cpu issue for the hosts

May 21 18:45:34 dhcp-0-198 kernel: kvm [3247]: vcpu0 unhandled rdmsr: 0x345
May 21 18:45:34 dhcp-0-198 kernel: kvm [3247]: vcpu0 unhandled wrmsr: 0x680 data 0
May 21 18:45:34 dhcp-0-198 kernel: kvm [3245]: vcpu0 unhandled rdmsr: 0x345
May 21 18:45:34 dhcp-0-198 kernel: kvm [3245]: vcpu0 unhandled wrmsr: 0x680 data 0
May 21 18:45:34 dhcp-0-198 kernel: kvm [3245]: vcpu0 unhandled wrmsr: 0x6c0 data 0
May 21 18:45:34 dhcp-0-198 kernel: kvm [3245]: vcpu0 unhandled wrmsr: 0x681 data 0
May 21 18:45:34 dhcp-0-198 kernel: kvm [3245]: vcpu0 unhandled wrmsr: 0x6c1 data 0
May 21 18:45:34 dhcp-0-198 kernel: kvm [3245]: vcpu0 unhandled wrmsr: 0x682 data 0
May 21 18:45:34 dhcp-0-198 kernel: kvm [3245]: vcpu0 unhandled wrmsr: 0x6c2 data 0
May 21 18:45:34 dhcp-0-198 kernel: kvm [3245]: vcpu0 unhandled wrmsr: 0x683 data 0
May 21 18:45:34 dhcp-0-198 kernel: kvm [3245]: vcpu0 unhandled wrmsr: 0x6c3 data 0
May 21 18:45:34 dhcp-0-198 kernel: kvm [3245]: vcpu0 unhandled wrmsr: 0x684 data 0
May 21 18:45:34 dhcp-0-198 kernel: kvm [3249]: vcpu0 unhandled rdmsr: 0x345
May 21 18:45:40 dhcp-0-198 kvm: 2 guests now active
May 21 18:45:40 dhcp-0-198 kvm: 1 guest now active

when I logged in to the ovirt engine vm I could see that hosts fail to activate because a wrong cpu type. 

This seems to happen since the cpu type has been selected based on the HW in which I created the image. 
hence, if I try to use the image in lago in any computer that has a different cpu it would not be able to activate the ovirt hosts.

**Comment by nvgoldin** [comment]
thanks for reporting: this is an issue with the 'lago ovirt start' method mainly - we need to change the cluster CPU family if it changed. I'm moving this to https://github.com/lago-project/lago-ost-plugin/issues/7
