### ISSUE TITLE
Lago storage (nfs and iscsi servers) templates are FC20 - should be updated

### ISSUE THREAD

**Issue by david-caro** [lago-project/lago#57]
Not sure this goes here, maybe will move to lago-poject/lago-images

Moved from https://bugzilla.redhat.com/show_bug.cgi?id=1273026
Description of problem:
The hosts templates are fc20 based 
this version is no longer supported by ovirt

**Comment by mykaul** [comment]
It's more important to unify them into a single image, btw.
I'd consider having them as CentOS/RHEL 7.2 - same as the hosts (so we could put Gluster on all 3).
This way they can also share the template, which will save space and maintenance.

**Comment by david-caro** [comment]
CentOS 7.2 would be best imo, it's already on libguestfs repos and we just need to tweak it a bit (add guest-tools).

**Comment by eedri** [comment]
Was this solved by the new EL7 images patch merged recently?

**Comment by gbenhaim** [comment]
For now we don't want to support pre-installed images (such a storage).
