### ISSUE TITLE
/dev/urandom is not supported in libvirt 1.3 - which is the default on ubuntu 16.04

### ISSUE THREAD

**Issue by nvgoldin** [lago-project/lago#572]

**Comment by dominikholler** [comment]
Does this mean 7a596a72a4717d272cbe8c74bd3b8c49f824063c has to be reverted?

**Comment by nvgoldin** [comment]
Nope, My idea is to improve the templates mechanism and add a condition there according to the libvirt version installed. Sysprep templates work already begun in https://github.com/lago-project/lago/pull/554, next is the domains.
