### ISSUE TITLE
pip: publish to PyPi automatically 

### ISSUE THREAD

**Issue by nvgoldin** [lago-project/lago#574]
1. Per 'check-merged' publish sdist to http://testpypi.python.org/
2. On release publish alongside RPMs the sdist to http://pypi.python.org/

**Comment by ifireball** [comment]
Looks like you'll either need us to finish implementing [OVIRT-894][1] or to add some functionality to automatically find sdists in 'exported-artifacts' and publish them.

BTW shouldn't we also be pushing wheels to make like easier for users?

[1]: https://ovirt-jira.atlassian.net/browse/OVIRT-894]

**Comment by nvgoldin** [comment]
@ifireball - Looked at [OVIRT-894][1] - sounds good.To begin with I plan to add it to our deploy-to scripts(which we already use now to publish RPMs) and add there the upload command using twine. The exported-artifacts jobs always generates also the sdist(alongside RPMs). And also turns out repoman when using '--with-sources' option takes them too(though I always thought that this was for SRPMS, but it it takes both(srpm and .tar.gz))


> BTW shouldn't we also be pushing wheels to make like easier for users?

Makes sense, will need to look into that.




[1]: https://ovirt-jira.atlassian.net/browse/OVIRT-894]

**Comment by nvgoldin** [comment]
@david-caro - I sent you an email(hope I had the right address) - I found out that you already registered the lago package back then in 0.4 on PyPi - so could you please grant permissions to my user(nvgoldin) or to the 'lago-bot' user? 
Thanks


https://pypi.python.org/pypi/lago

**Comment by nvgoldin** [comment]
Urgh!, so turns out the .tar.gz repoman produces is actually the result of running 'rpm2cpio' on the rpm(at least from a shallow look at repoman code) and not the '.tar.gz' sdist we produce in the artifacts. That is of course not installable by pip, need to fix and to deploy the correct .tar.gz to pypi.

**Comment by gbenhaim** [comment]
I think that we can also remove this tar version of the rpm from our repo - will help to avoid more confusion in the future.

**Comment by nvgoldin** [comment]
@gbenhaim - maybe it makes some sense in RPM way, though I agree. Will need to check if we can repoman to publish `srpms` but not that .tar.gz. 
Anyways, hopefully fixed the script for the deploy-to-snapshot, next merged patch will tell.

**Comment by nvgoldin** [comment]
Fixed since 0.40.
