### ISSUE TITLE
info level message of ``Acquiring lock for /var/lib/lago/subnets/leases`` on lago init

### ISSUE THREAD

**Issue by nvgoldin** [lago-project/lago#597]
```
18:32:06   # Acquiring lock for /var/lib/lago/subnets/leases: 
18:32:06   # Acquiring lock for /var/lib/lago/subnets/leases: Success (in 0:00:00)
18:32:06   # Acquiring lock for /var/lib/lago/subnets/leases: 
18:32:06   # Acquiring lock for /var/lib/lago/subnets/leases: Success (in 0:00:00)
18:32:06   # Acquiring lock for /var/lib/lago/subnets/leases: 
18:32:06   # Acquiring lock for /var/lib/lago/subnets/leases: Success (in 0:00:00)
```

@gbenhaim - not sure if this was intentional in https://github.com/lago-project/lago/commit/0c8de17447683c1f3ca8da02929d9f27b13cc099 (maybe the logdepth is <= 3 now?), anyways, I don't think it should be printed at `info` level, as this is really a behind-the-scene implementation detail. 
.

**Comment by gbenhaim** [comment]
It's not something new:

`ccf6dca483c1c59b3ffddb6847045bc77f07e04f`

**Comment by gbenhaim** [comment]
I can change the logging in the context manager to debug level.

**Comment by gbenhaim** [comment]
fixed by https://github.com/lago-project/lago/pull/602
