### ISSUE TITLE
subnets: free leases on destroy

### ISSUE THREAD

**Issue by nvgoldin** [lago-project/lago#599]
@gbenhaim  - I have second thoughts about:
https://github.com/lago-project/lago/blob/master/lago/subnet_lease.py#L59-L61
```
  Cleanup of stale leases is done in a lazy manner during a request for a
    lease. The store will remove at most 1 stale lease in each request (see
    SubnetStore._lease_valid for more info).
```

Why don't we release the subnet in the prefix destroy method? It only makes sense that when you destroy an environment you would free the subnet, instead of waiting for a different invocation that would clean it up for you. 
The "lazy manner" removal can still be kept, but it is less reliable(as you might not have access to the environment to know if it still exists).

Missed something here?

**Comment by gbenhaim** [comment]
Agree, we should add subnet cleanup when destroying an env.
