### ISSUE TITLE
Bug 1294464 - [RFE] Improve the docs for lago 

### ISSUE THREAD

**Issue by eedri** [lago-project/lago#6]
Description of problem:
I tried to setup lago a few days ago and I think the docs need improvement, here were the parts that I think should be changed:

1. Ordering to avoid reboots. Currently several reboots are needed to get a working system this can be reduced:
   - Changing config to enable nested.
   - Changing SELinux to be permissive.
   - Enabling libvirt by default.
   - Users permissions changes.

Then reboot:
   - Changing BIOS if needed.
   - Check libvirt enabled.
   - Check SELinux permissive.

This ensures that lago remains working after reboot.

2. You do not suggest a default user name to use for lago and list it in the examples. I chose user name lago, which was not a good idea which many users will do.

3. There is no way to know the default prefixes and how to change them.
"""
Make sure that the qemu user has execution rights to the dir where you will be creating the prefixes, you can try it out with:

$ sudo -u qemu ls /path/to/the/destination/dir
"""
  There is no way for me to know what path to check and what prefixes are used. Please make this more explicit.

Migrated from: https://bugzilla.redhat.com/show_bug.cgi?id=1294464

**Comment by david-caro** [comment]
Fixed by #177
