### ISSUE TITLE
Drop Fedora 24

### ISSUE THREAD

**Issue by nvgoldin** [lago-project/lago#636]
We've already been building fc26 RPMs for a while, only need to publish them.
I guess we can do a dual release(fc24 and fc26) in version(v0.41) and in (v0.42) drop fc24.

**Comment by gbenhaim** [comment]
I've added manually lago v.040 for fc26 to production repo (also added it to the deploy-to-production script).

**Comment by gbenhaim** [comment]
Done https://gerrit.ovirt.org/c/83421/
