### ISSUE TITLE
running Lago from using remote user (like LDAP) fails due to permission error

### ISSUE THREAD

**Issue by eedri** [lago-project/lago#638]
When using a remote user on a local machine ( like LDAP on RHEL CSB ), the initial permission settings done on local groups don't work and running Lago or OST fails due to permission error.

don't have the errors anymore, but it should be easily reproduced by:

1. running install_lago.sh on a new CSB 7.3
2. running ost suite

**Comment by gbenhaim** [comment]
https://github.com/lago-project/lago/pull/640

**Comment by gbenhaim** [comment]
We decided that the best approach will be to notify the user about the issue and how it can
be solved.

Fixed in https://github.com/lago-project/lago/pull/640
