### ISSUE TITLE
Bug 1291753 - Lago needs a TL;DR mission statement 

### ISSUE THREAD

**Issue by eedri** [lago-project/lago#7]
Description of problem:
There is nowhere to go to get a simple answer to the question "What is Lago" and more importantly "What can it do for me"

Expected results:
There should be a one-paragraph answer featured prominently at the beginning of the README file and on the top of every page we thing people will come top to lean about Lago.

**Comment by ifireball** [comment]
Come on, that 8-word sentence hardly says anything. do I need to
s/TL;DR/clear TL;DR/ ?

On 15 March 2016 at 15:01, Lago CI bot <notifications@github.com> wrote:

> Closed #7 <https://github.com/lago-project/lago/issues/7> via 9b6d466
> <https://github.com/lago-project/lago/commit/9b6d4665b4502dbd2184cdc91f91f30cfef4cebc>
> .
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/lago-project/lago/issues/7#event-590225202
>



-- 
*Barak Korren*
bkorren@redhat.com
RHEV-CI Team

**Comment by david-caro** [comment]
Feel free to try to write something more concrete, but that's the most concrete summary that I was able to come up with

**Comment by david-caro** [comment]
and it's probably going to change sooner than later...
