### ISSUE TITLE
 Create prefix internal repo seems stuck because reposync is running (and may take a lot of time)

### ISSUE THREAD

**Issue by mykaul** [lago-project/lago#71]
If you have a long reposync (I've had a 10 minutes), all you see is:
@ Initialize and populate prefix: Success (in 0:00:12)
@ Create prefix internal repo: 

This is very annoying - there is absolutely no progress, so it seems like stuck.
I suggest output reposync to the screen - I think it's fine, either it should not have a lot of output and complete fast, or it will, so the user will know there is progress

BTW, after all worked, it took 10 minutes (from the BRQ office - I assume when I was on the airport wifi it could have taken an hour!)

**Comment by david-caro** [comment]
Fixed with the latest reposync improvements
