### ISSUE TITLE
Bug 1291079 - [DOC] add info for a minimum and recommended hardware for a host to run lago on. 

### ISSUE THREAD

**Issue by eedri** [lago-project/lago#8]
Description of problem:
Lago installation README needs to include a minimum and recomended hardware specs for running lago on.

Something like:
Minimum: 12GB Ram, 2 CPU?
Recomended: 32GB, 4 CPU...

**Comment by eedri** [comment]
That does not make much sense, as it depends of what you are running (I'm running lago functional tests with a 64Mb ram vm with 7Mb disk image...).

For the ovirt tests, we are already describing more or less what you will need, maybe that's what you mean?

**Comment by nvgoldin** [comment]
closing, this is OST related and fixed:

**Comment by nvgoldin** [comment]
closing, this is OST related and fixed:
http://ovirt-system-tests.readthedocs.io/en/latest/docs/general/installation.html
