### ISSUE TITLE
Unable to Top Up Credit Balance

### ISSUE THREAD

**Issue by Setom29** [lago-project/lago#823]
I'm encountering an issue when trying to top up the credit balance in one of the test wallets on our pre-production self-hosted Lago service. The operation fails both via the interface and the API, with the following error in logs:
```
ActiveRecord::StatementInvalid (PG::UndefinedFunction: ERROR: function unaccent(character varying) does not exist  
LINE 1: ... ORDER BY lower(unaccent(...  
HINT: No function matches the given name and argument types. You might need to add explicit type casts.
```
Could you point me in the right direction for resolving it?
Thanks in advance!

**Comment by ifireball** [comment]
Sir, I think you got the wrong project. This project has nothing to do with wallets or credit balance.
