### ISSUE TITLE
Bug 1287803 - Lago yum repo needs symlinks for el7 flavors

### ISSUE THREAD

**Issue by eedri** [lago-project/lago#9]
Description of problem:
When following the Lago README and setting up a repo file on EL7 with the following URL:

http://resources.ovirt.org/repos/lago/rpm/el$releasever

The repo doesn't work, and yum returns the following error:

http://resources.ovirt.org/repos/lago/rpm/el7Workstation/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.

A symlink needs to be created from el7Workstation to el7, probably for el7Server too.

**Comment by david-caro** [comment]
Done
