### ISSUE TITLE
Use direct backend for libguestfs where possible

### ISSUE THREAD

**Issue by david-caro** [lago-project/lago#94]
To avoid getting issues at bootstrap and similar, at least until https://bugzilla.redhat.com/show_bug.cgi?id=1271183 is fixed

**Comment by mykaul** [comment]
That's a good idea - I use it without any issues for some time now. Two more enhancements:
export LIBGUESTFS_CACHEDIR=/home/zram
export LIBGUESTFS_TMPDIR=/home/zram

Both go into my ZRAM drive.

**Comment by david-caro** [comment]
Those suggestions are a little bit more complicated to get it by default, I think they should be set as configuration options if any

**Comment by mykaul** [comment]
just saying that the cache dir and temp dir should be on the same location as the output of the test.

**Comment by david-caro** [comment]
Oh, I don't really agree with that, why should temporary dirs not use the system provided temporary dirs?

**Comment by mykaul** [comment]
If you run on ZRAM (or /dev/shm/<somewhere> ) it is faster.

**Comment by david-caro** [comment]
but that's a very specific use case, I don't think that most users will go that way

**Comment by david-caro** [comment]
that's why I said to let specify it in the config file, so you can set it yourself, but the default should be the most generic use case imo

**Comment by david-caro** [comment]
@mykaul opened another issue for the two extra config options
